server:
  port: 9000

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:AuthenticationServiceDB}
    username: ${POSTGRES_USER:auth-service-user}
    password: ${POSTGRES_PASSWORD:odn1Dl}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: off
    database: postgresql

  liquibase:
    change-log: classpath:/db/changelog.xml
    enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: rankingapp473@gmail.com
    password: qeyp robi howh klut
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

springdoc:
  swagger-ui:
    path: /auth-service/swagger-ui
  api-docs:
    path: /auth-service/v3/api-docs

logging:
  level:
    root: INFO
    web: WARN
    org.springdoc: DEBUG

security:
  jwt:
    secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expires-in: 12960000

email:
  code:
    confirmation:
      sender-email: rankingapp473@gmail.com
      subject-text: Код подтверждения
