version: '3.8'

services:

  ranking-app-service:
    image: maxim777/rankingapp-ranking-app-service:latest 
    build: .
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      ranking-app-service-database:
        condition: service_started
    environment:
      DB_HOST: ranking-app-service-database
      DB_PORT: 8000
      POSTGRES_USER: ranking-app-user
      POSTGRES_PASSWORD: odn1Dl
      spring.liquibase.enabled: true
    volumes:
      - file-storage:/uploads
    networks:
      - ranking-app-network

  ranking-app-service-database:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: ranking-app-user
      POSTGRES_PASSWORD: odn1Dl
      POSTGRES_DB: RankingAppDB
    ports:
      - "5436:8000"
    volumes:
      - ./postgres-data:/var/lib/ranking-app-service-database/data
    command: -p 8000
    networks:
      - ranking-app-network

networks:
  ranking-app-network:
    driver: bridge

volumes:
  postgres-data:
  file-storage:
