version: '3.8'

services:

  ranking-app-service:
    image: maxim777/rankingapp-ranking-app-service:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      ranking-app-service-database:
        condition: service_started
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      ADD_TO_ORG_URL: ${ADD_TO_ORG_URL}
      RECOVERY_URL: ${RECOVERY_URL}
      CURATOR_URL: ${CURATOR_URL}
      FRONT_MAIN_URL: ${FRONT_MAIN_URL}
      PAYMENT_KEY: ${PAYMENT_KEY}
      PAYMENT_ID: ${PAYMENT_ID}
      spring.liquibase.enabled: "true"
    volumes:
      - file-storage:/uploads
    networks:
      - ranking-app-network

  ranking-app-service-database:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5436:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ranking-app-network

networks:
  ranking-app-network:
    driver: bridge

volumes:
  postgres-data:
  file-storage:
