server:
  port: 9000

spring:
  main:
    allow-circular-references: true
  application:
    name: ranking-app

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:RankingAppDB}
    username: ${POSTGRES_USER:ranking-app-user}
    password: ${POSTGRES_PASSWORD:odn1Dl}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog.xml
    enabled: true
    clear-checksums: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: rankingapp473@gmail.com
    password: qeyp robi howh klut
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

springdoc:
  swagger-ui:
    path: /ranking-app/swagger-ui
  api-docs:
    path: /ranking-app/v3/api-docs

logging:
  level:
    root: INFO  # Уровень логирования для всего приложения
    web: WARN   # Уровень логирования для веб-слоя
    org:
      springframework:
        security: DEBUG  # Логирование Spring Security
        web: DEBUG       # Логирование Spring Web
      hibernate:
        sql: DEBUG       # Логирование SQL-запросов
        orm:
          jdbc:
            bind: TRACE # Логирование параметров SQL-запросов
    ru:
      hse:
        rankingapp: DEBUG

security:
  jwt:
    secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expires-in: 12960000

email:
  code:
    confirmation:
      sender-email: rankingapp473@gmail.com
      subject-text: Код подтверждения
