name: Build and Deploy

on:
  push:
    branches: [ "ci-cd" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push app

      - name: Deploy to Yandex Cloud VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.YC_VM_HOST }}
          username: ${{ secrets.YC_VM_USER }}
          key: ${{ secrets.YC_VM_SSH_KEY }}
          script: |
            docker compose -f /path/to/docker-compose.yml pull app
            docker compose -f /path/to/docker-compose.yml up -d
