name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t maxim777/rankingapp-ranking-app-service:latest .
          docker push maxim777/rankingapp-ranking-app-service:latest
  
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.YC_VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.YC_VM_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
      - name: Ensure directory exists
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.YC_VM_HOST }}
          username: ${{ secrets.YC_VM_USER }}
          key: ${{ secrets.YC_VM_SSH_KEY }}
          script: |
            sudo mkdir -p /backend
            sudo chown -R $USER:$USER /backend
            sudo chmod 755 /backend
            sudo mkdir -p /backend/postgres
            sudo chown -R $USER:$USER /backend/postgres
            sudo chmod 755 /backend/postgres
            sudo mkdir -p /backend/postgres/init-scripts
            sudo chown -R $USER:$USER /backend/postgres/init-scripts
            sudo chmod 755 /backend/postgres/init-scripts
          
      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.YC_VM_HOST }}
          username: ${{ secrets.YC_VM_USER }}
          key: ${{ secrets.YC_VM_SSH_KEY }}
          source: "docker-compose.yaml"
          target: "/backend/"
          strip_components: 0  # Сохранять структуру директорий
          overwrite: true  # Разрешить перезапись

      - name: Copy postgres/Dockerfile to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.YC_VM_HOST }}
          username: ${{ secrets.YC_VM_USER }}
          key: ${{ secrets.YC_VM_SSH_KEY }}
          source: "postgres/"
          target: "/backend/"
          strip_components: 0  # Сохранять структуру директорий
          overwrite: true  # Разрешить перезапись
          
      - name: Deploy to Yandex Cloud VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.YC_VM_HOST }}
          username: ${{ secrets.YC_VM_USER }}
          key: ${{ secrets.YC_VM_SSH_KEY }}
          script: |
            cd /backend
            docker-compose stop ranking-app-service
            docker-compose rm -f ranking-app-service
            docker-compose pull ranking-app-service
            docker-compose up -d --no-deps ranking-app-service
